version: '3.3'

services:
  db:
    image: postgres
    container_name: docker-django-vue-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  django:
    build:
      context: ./backend/
      dockerfile: ./BackendDockerfile      
    container_name: docker-django-vue-backend  
    command: ./backend_setup.sh
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  vue:
    build:
      context: ./frontend/
      dockerfile: ./FrontendDockerfile
    container_name: docker-django-vue-frontend
    command: ./frontend_setup.sh
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8080:8080"
    depends_on:
      - django
volumes:
  db-data: