// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddVisitorCount(ctx context.Context, visitorID uuid.UUID) (Visitor, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateVisitor(ctx context.Context, arg CreateVisitorParams) (Visitor, error)
	DeleteVisitor(ctx context.Context, visitorID uuid.UUID) error
	GetAdmin(ctx context.Context, adminName string) (Admin, error)
	GetSession(ctx context.Context, sessionID uuid.UUID) (Session, error)
	GetVisitor(ctx context.Context, visitorID uuid.UUID) (Visitor, error)
	ListVisitors(ctx context.Context, arg ListVisitorsParams) ([]Visitor, error)
	UpdateVisitor(ctx context.Context, arg UpdateVisitorParams) (Visitor, error)
}

var _ Querier = (*Queries)(nil)
