# Generated by Django 3.1.13 on 2021-10-30 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_auto_20211026_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visits_count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
